/*
 *  Copyright (c) 2018-present, Aleksandr Telegin
 *  The data are taken from Wikipedia
 *
 * This source code is licensed under the GPL v.3.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { getPhoneCode } from 'libphonenumber-js';
import '../../node_modules/flag-icon-css/css/flag-icon.css';

const COUNTRY_NAMES_EN = {
        AF: 'Afghanistan',
        AL: 'Albania',
        DZ: 'Algeria',
        AS: 'American Samoa',
        AD: 'Andorra',
        AO: 'Angola',
        AI: 'Anguilla',
        AQ: 'Antarctica',
        AG: 'Antigua and Barbuda',
        AR: 'Argentina',
        AM: 'Armenia',
        AW: 'Aruba',
        AU: 'Australia',
        AT: 'Austria',
        AZ: 'Azerbaijan',
        BS: 'Bahamas',
        BH: 'Bahrain',
        BD: 'Bangladesh',
        BB: 'Barbados',
        BY: 'Belarus',
        BE: 'Belgium',
        BZ: 'Belize',
        BJ: 'Benin',
        BM: 'Bermuda',
        BT: 'Bhutan',
        BO: 'Bolivia',
        BA: 'Bosnia and Herzegovina',
        BW: 'Botswana',
        BR: 'Brazil',
        IO: 'British Indian Ocean Territory',
        VG: 'British Virgin Islands',
        BN: 'Brunei',
        BG: 'Bulgaria',
        BF: 'Burkina Faso',
        BI: 'Burundi',
        KH: 'Cambodia',
        CM: 'Cameroon',
        CA: 'Canada',
        CV: 'Cape Verde',
        KY: 'Cayman Islands',
        CF: 'Central African Republic',
        TD: 'Chad',
        CL: 'Chile',
        CN: 'China',
        CX: 'Christmas Island',
        CC: 'Cocos Islands',
        CO: 'Colombia',
        KM: 'Comoros',
        CK: 'Cook Islands',
        CR: 'Costa Rica',
        HR: 'Croatia',
        CU: 'Cuba',
        CW: 'Curacao',
        CY: 'Cyprus',
        CZ: 'Czech Republic',
        CD: 'Democratic Republic of the Congo',
        DK: 'Denmark',
        DJ: 'Djibouti',
        DM: 'Dominica',
        DO: 'Dominican Republic',
        TL: 'East Timor',
        EC: 'Ecuador',
        EG: 'Egypt',
        SV: 'El Salvador',
        GQ: 'Equatorial Guinea',
        ER: 'Eritrea',
        EE: 'Estonia',
        ET: 'Ethiopia',
        FK: 'Falkland Islands',
        FO: 'Faroe Islands',
        FJ: 'Fiji',
        FI: 'Finland',
        FR: 'France',
        PF: 'French Polynesia',
        GA: 'Gabon',
        GM: 'Gambia',
        GE: 'Georgia',
        DE: 'Germany',
        GH: 'Ghana',
        GI: 'Gibraltar',
        GR: 'Greece',
        GL: 'Greenland',
        GD: 'Grenada',
        GU: 'Guam',
        GT: 'Guatemala',
        GG: 'Guernsey',
        GN: 'Guinea',
        GW: 'Guinea-Bissau',
        GY: 'Guyana',
        HT: 'Haiti',
        HN: 'Honduras',
        HK: 'Hong Kong',
        HU: 'Hungary',
        IS: 'Iceland',
        IN: 'India',
        ID: 'Indonesia',
        IR: 'Iran',
        IQ: 'Iraq',
        IE: 'Ireland',
        IM: 'Isle of Man',
        IL: 'Israel',
        IT: 'Italy',
        CI: 'Ivory Coast',
        JM: 'Jamaica',
        JP: 'Japan',
        JE: 'Jersey',
        JO: 'Jordan',
        KZ: 'Kazakhstan',
        KE: 'Kenya',
        KI: 'Kiribati',
        XK: 'Kosovo',
        KW: 'Kuwait',
        KG: 'Kyrgyzstan',
        LA: 'Laos',
        LV: 'Latvia',
        LB: 'Lebanon',
        LS: 'Lesotho',
        LR: 'Liberia',
        LY: 'Libya',
        LI: 'Liechtenstein',
        LT: 'Lithuania',
        LU: 'Luxembourg',
        MO: 'Macau',
        MK: 'Macedonia',
        MG: 'Madagascar',
        MW: 'Malawi',
        MY: 'Malaysia',
        MV: 'Maldives',
        ML: 'Mali',
        MT: 'Malta',
        MH: 'Marshall Islands',
        MR: 'Mauritania',
        MU: 'Mauritius',
        YT: 'Mayotte',
        MX: 'Mexico',
        FM: 'Micronesia',
        MD: 'Moldova',
        MC: 'Monaco',
        MN: 'Mongolia',
        ME: 'Montenegro',
        MS: 'Montserrat',
        MA: 'Morocco',
        MZ: 'Mozambique',
        MM: 'Myanmar',
        NA: 'Namibia',
        NR: 'Nauru',
        NP: 'Nepal',
        NL: 'Netherlands',
        AN: 'Netherlands Antilles',
        NC: 'New Caledonia',
        NZ: 'New Zealand',
        NI: 'Nicaragua',
        NE: 'Niger',
        NG: 'Nigeria',
        NU: 'Niue',
        KP: 'North Korea',
        MP: 'Northern Mariana Islands',
        NO: 'Norway',
        OM: 'Oman',
        PK: 'Pakistan',
        PW: 'Palau',
        PS: 'Palestine',
        PA: 'Panama',
        PG: 'Papua New Guinea',
        PY: 'Paraguay',
        PE: 'Peru',
        PH: 'Philippines',
        PN: 'Pitcairn',
        PL: 'Poland',
        PT: 'Portugal',
        PR: 'Puerto Rico',
        QA: 'Qatar',
        CG: 'Republic of the Congo',
        RE: 'Reunion',
        RO: 'Romania',
        RU: 'Russia',
        RW: 'Rwanda',
        BL: 'Saint Barthelemy',
        SH: 'Saint Helena',
        KN: 'Saint Kitts and Nevis',
        LC: 'Saint Lucia',
        MF: 'Saint Martin',
        PM: 'Saint Pierre and Miquelon',
        VC: 'Saint Vincent and the Grenadines',
        WS: 'Samoa',
        SM: 'San Marino',
        ST: 'Sao Tome and Principe',
        SA: 'Saudi Arabia',
        SN: 'Senegal',
        RS: 'Serbia',
        SC: 'Seychelles',
        SL: 'Sierra Leone',
        SG: 'Singapore',
        SX: 'Sint Maarten',
        SK: 'Slovakia',
        SI: 'Slovenia',
        SB: 'Solomon Islands',
        SO: 'Somalia',
        ZA: 'South Africa',
        KR: 'South Korea',
        SS: 'South Sudan',
        ES: 'Spain',
        LK: 'Sri Lanka',
        SD: 'Sudan',
        SR: 'Suriname',
        SJ: 'Svalbard and Jan Mayen',
        SZ: 'Swaziland',
        SE: 'Sweden',
        CH: 'Switzerland',
        SY: 'Syria',
        TW: 'Taiwan',
        TJ: 'Tajikistan',
        TZ: 'Tanzania',
        TH: 'Thailand',
        TG: 'Togo',
        TK: 'Tokelau',
        TO: 'Tonga',
        TT: 'Trinidad and Tobago',
        TN: 'Tunisia',
        TR: 'Turkey',
        TM: 'Turkmenistan',
        TC: 'Turks and Caicos Islands',
        TV: 'Tuvalu',
        VI: 'U.S. Virgin Islands',
        UG: 'Uganda',
        UA: 'Ukraine',
        AE: 'United Arab Emirates',
        GB: 'United Kingdom',
        US: 'United States',
        UY: 'Uruguay',
        UZ: 'Uzbekistan',
        VU: 'Vanuatu',
        VA: 'Vatican',
        VE: 'Venezuela',
        VN: 'Vietnam',
        WF: 'Wallis and Futuna',
        EH: 'Western Sahara',
        YE: 'Yemen',
        ZM: 'Zambia',
        ZW: 'Zimbabwe'
    },
    COUNTRY_NAMES_RU = {
        AU: 'Австралия',
        AT: 'Австрия',
        AZ: 'Азербайджан',
        AL: 'Албания',
        DZ: 'Алжир',
        AS: 'Американское Самоа',
        AI: 'Ангилья',
        AO: 'Ангола',
        AD: 'Андорра',
        AQ: 'Антарктида',
        AG: 'Антигуа и Барбуда',
        AR: 'Аргентина',
        AM: 'Армения',
        AW: 'Аруба',
        AF: 'Афганистан',
        BS: 'Багамы',
        BD: 'Бангладеш',
        BB: 'Барбадос',
        BH: 'Бахрейн',
        BY: 'Беларусь',
        BZ: 'Белиз',
        BE: 'Бельгия',
        BJ: 'Бенин',
        BM: 'Бермуды',
        BG: 'Болгария',
        BO: 'Боливия',
        BA: 'Босния и Герцеговина',
        BW: 'Ботсвана',
        BR: 'Бразилия',
        IO: 'Британская территория в Индийском океане',
        BN: 'Бруней',
        BF: 'Буркина-Фасо',
        BI: 'Бурунди',
        BT: 'Бутан',
        VU: 'Вануату',
        HU: 'Венгрия',
        VE: 'Венесуэла',
        VG: 'Виргинские острова (Британские)',
        VI: 'Виргинские острова (США)',
        VN: 'Вьетнам',
        GA: 'Габон',
        HT: 'Гаити',
        GY: 'Гайана',
        GM: 'Гамбия',
        GH: 'Гана',
        GT: 'Гватемала',
        GN: 'Гвинея',
        GW: 'Гвинея-Бисау',
        DE: 'Германия',
        GG: 'Гернси',
        GI: 'Гибралтар',
        HN: 'Гондурас',
        HK: 'Гонконг',
        GD: 'Гренада',
        GL: 'Гренландия',
        GR: 'Греция',
        GE: 'Грузия',
        GU: 'Гуам',
        DK: 'Дания',
        JE: 'Джерси',
        DJ: 'Джибути',
        DM: 'Доминика',
        DO: 'Доминиканская Республика',
        EG: 'Египет',
        ZM: 'Замбия',
        EH: 'Западная Сахара',
        ZW: 'Зимбабве',
        IL: 'Израиль',
        IN: 'Индия',
        ID: 'Индонезия',
        JO: 'Иордания',
        IQ: 'Ирак',
        IR: 'Иран',
        IE: 'Ирландия',
        IS: 'Исландия',
        ES: 'Испания',
        IT: 'Италия',
        YE: 'Йемен',
        CV: 'Кабо-Верде',
        KZ: 'Казахстан',
        KH: 'Камбоджа',
        CM: 'Камерун',
        CA: 'Канада',
        QA: 'Катар',
        KE: 'Кения',
        CY: 'Кипр',
        KG: 'Киргизия',
        KI: 'Кирибати',
        CN: 'Китай',
        CC: 'Кокосовые (Килинг) острова',
        CO: 'Колумбия',
        KM: 'Коморы',
        CG: 'Конго',
        CD: 'Конго, Демократическая Республика',
        KP: 'Корея, Народно-Демократическая Республика',
        KR: 'Корея, Республика',
        CR: 'Коста-Рика',
        CI: "Кот д'Ивуар",
        CU: 'Куба',
        KW: 'Кувейт',
        CW: 'Кюрасао',
        LA: 'Лаос',
        LV: 'Латвия',
        LS: 'Лесото',
        LB: 'Ливан',
        LY: 'Ливия',
        LR: 'Либерия',
        LI: 'Лихтенштейн',
        LT: 'Литва',
        LU: 'Люксембург',
        MU: 'Маврикий',
        MR: 'Мавритания',
        MG: 'Мадагаскар',
        YT: 'Майотта',
        MO: 'Макао',
        MW: 'Малави',
        MY: 'Малайзия',
        ML: 'Мали',
        MV: 'Мальдивы',
        MT: 'Мальта',
        MA: 'Марокко',
        MH: 'Маршалловы острова',
        MX: 'Мексика',
        FM: 'Микронезия, Федеративные Штаты',
        MZ: 'Мозамбик',
        MD: 'Молдова',
        MC: 'Монако',
        MN: 'Монголия',
        MS: 'Монтсеррат',
        MM: 'Мьянма',
        NA: 'Намибия',
        NR: 'Науру',
        NP: 'Непал',
        NE: 'Нигер',
        NG: 'Нигерия',
        NL: 'Нидерланды',
        NI: 'Никарагуа',
        NU: 'Ниуэ',
        NZ: 'Новая Зеландия',
        NC: 'Новая Каледония',
        NO: 'Норвегия',
        AE: 'Объединенные Арабские Эмираты',
        OM: 'Оман',
        IM: 'Остров Мэн',
        CX: 'Остров Рождества',
        KY: 'Острова Кайман',
        CK: 'Острова Кука',
        TC: 'Острова Теркс и Кайкос',
        PK: 'Пакистан',
        PW: 'Палау',
        PS: 'Палестинская территория',
        PA: 'Панама',
        VA: 'Ватикан',
        PG: 'Папуа-Новая Гвинея',
        PY: 'Парагвай',
        PE: 'Перу',
        PN: 'Питкерн',
        PL: 'Польша',
        PT: 'Португалия',
        PR: 'Пуэрто-Рико',
        MK: 'Республика Македония',
        RE: 'Реюньон',
        RU: 'Россия',
        RW: 'Руанда',
        RO: 'Румыния',
        WS: 'Самоа',
        SM: 'Сан-Марино',
        ST: 'Сан-Томе и Принсипи',
        SA: 'Саудовская Аравия',
        SZ: 'Свазиленд',
        SH: 'Святая Елена',
        MP: 'Северные Марианские острова',
        BL: 'Сен-Бартельми',
        MF: 'Сен-Мартен',
        SN: 'Сенегал',
        VC: 'Сент-Винсент и Гренадины',
        KN: 'Сент-Китс и Невис',
        LC: 'Сент-Люсия',
        PM: 'Сент-Пьер и Микелон',
        RS: 'Сербия',
        SC: 'Сейшелы',
        SG: 'Сингапур',
        SX: 'Синт-Мартен',
        SY: 'Сирия',
        SK: 'Словакия',
        SI: 'Словения',
        GB: 'Соединенное Королевство',
        US: 'Соединенные Штаты',
        SB: 'Соломоновы острова',
        SO: 'Сомали',
        SD: 'Судан',
        SR: 'Суринам',
        SL: 'Сьерра-Леоне',
        TJ: 'Таджикистан',
        TH: 'Таиланд',
        TW: 'Тайвань',
        TZ: 'Танзания',
        TL: 'Тимор-Лесте',
        TG: 'Того',
        TK: 'Токелау',
        TO: 'Тонга',
        TT: 'Тринидад и Тобаго',
        TV: 'Тувалу',
        TN: 'Тунис',
        TM: 'Туркмения',
        TR: 'Турция',
        UG: 'Уганда',
        UZ: 'Узбекистан',
        UA: 'Украина',
        WF: 'Уоллис и Футуна',
        UY: 'Уругвай',
        FO: 'Фарерские острова',
        FJ: 'Фиджи',
        PH: 'Филиппины',
        FI: 'Финляндия',
        FK: 'Фолклендские острова',
        FR: 'Франция',
        PF: 'Французская Полинезия',
        HR: 'Хорватия',
        CF: 'Центральноафриканская Республика',
        TD: 'Чад',
        ME: 'Черногория',
        CZ: 'Чешская Республика',
        CL: 'Чили',
        CH: 'Швейцария',
        SE: 'Швеция',
        SJ: 'Шпицберген и Ян Майен',
        LK: 'Шри-Ланка',
        EC: 'Эквадор',
        GQ: 'Экваториальная Гвинея',
        SV: 'Эль-Сальвадор',
        ER: 'Эритрея',
        EE: 'Эстония',
        ET: 'Эфиопия',
        ZA: 'Южная Африка',
        SS: 'Южный Судан',
        JM: 'Ямайка',
        JP: 'Япония'
    },
    PHONE_CODES = {
        AF: 93,
        AL: 355,
        DZ: 213,
        AS: 1684,
        AD: 376,
        AO: 244,
        AI: 1264,
        AQ: 672,
        AG: 1268,
        AR: 54,
        AM: 374,
        AW: 297,
        AU: 61,
        AT: 43,
        AZ: 994,
        BS: 1242,
        BH: 973,
        BD: 880,
        BB: 1246,
        BY: 375,
        BE: 32,
        BZ: 501,
        BJ: 229,
        BM: 1441,
        BT: 975,
        BO: 591,
        BA: 387,
        BW: 267,
        BR: 55,
        IO: 246,
        VG: 1284,
        BN: 673,
        BG: 359,
        BF: 226,
        BI: 257,
        KH: 855,
        CM: 237,
        US: 1,
        CA: 1,
        CV: 238,
        KY: 1345,
        CF: 236,
        TD: 235,
        CL: 56,
        CN: 86,
        CX: 61,
        CC: 61,
        CO: 57,
        KM: 269,
        CK: 682,
        CR: 506,
        HR: 385,
        CU: 53,
        CW: 599,
        CY: 357,
        CZ: 420,
        CD: 243,
        DK: 45,
        DJ: 253,
        DM: 1767,
        DO: 1809,
        TL: 670,
        EC: 593,
        EG: 20,
        SV: 503,
        GQ: 240,
        ER: 291,
        EE: 372,
        ET: 251,
        FK: 500,
        FO: 298,
        FJ: 679,
        FI: 358,
        FR: 33,
        PF: 689,
        GA: 241,
        GM: 220,
        GE: 995,
        DE: 49,
        GH: 233,
        GI: 350,
        GR: 30,
        GL: 299,
        GD: 1473,
        GU: 1671,
        GT: 502,
        GG: 441481,
        GN: 224,
        GW: 245,
        GY: 592,
        HT: 509,
        HN: 504,
        HK: 852,
        HU: 36,
        IS: 354,
        IN: 91,
        ID: 62,
        IR: 98,
        IQ: 964,
        IE: 353,
        IM: 441624,
        IL: 972,
        IT: 39,
        CI: 225,
        JM: 1876,
        JP: 81,
        JE: 441534,
        JO: 962,
        KE: 254,
        KI: 686,
        XK: 383,
        KW: 965,
        KG: 996,
        LA: 856,
        LV: 371,
        LB: 961,
        LS: 266,
        LR: 231,
        LY: 218,
        LI: 423,
        LT: 370,
        LU: 352,
        MO: 853,
        MK: 389,
        MG: 261,
        MW: 265,
        MY: 60,
        MV: 960,
        ML: 223,
        MT: 356,
        MH: 692,
        MR: 222,
        MU: 230,
        YT: 262,
        MX: 52,
        FM: 691,
        MD: 373,
        MC: 377,
        MN: 976,
        ME: 382,
        MS: 1664,
        MA: 212,
        MZ: 258,
        MM: 95,
        NA: 264,
        NR: 674,
        NP: 977,
        NL: 31,
        AN: 599,
        NC: 687,
        NZ: 64,
        NI: 505,
        NE: 227,
        NG: 234,
        NU: 683,
        KP: 850,
        MP: 1670,
        NO: 47,
        OM: 968,
        PK: 92,
        PW: 680,
        PS: 970,
        PA: 507,
        PG: 675,
        PY: 595,
        PE: 51,
        PH: 63,
        PN: 64,
        PL: 48,
        PT: 351,
        PR: 1787,
        QA: 974,
        CG: 242,
        RE: 262,
        RO: 40,
        RU: 7,
        KZ: 7,
        RW: 250,
        BL: 590,
        SH: 290,
        KN: 1869,
        LC: 1758,
        MF: 590,
        PM: 508,
        VC: 1784,
        WS: 685,
        SM: 378,
        ST: 239,
        SA: 966,
        SN: 221,
        RS: 381,
        SC: 248,
        SL: 232,
        SG: 65,
        SX: 1721,
        SK: 421,
        SI: 386,
        SB: 677,
        SO: 252,
        ZA: 27,
        KR: 82,
        SS: 211,
        ES: 34,
        LK: 94,
        SD: 249,
        SR: 597,
        SJ: 47,
        SZ: 268,
        SE: 46,
        CH: 41,
        SY: 963,
        TW: 886,
        TJ: 992,
        TZ: 255,
        TH: 66,
        TG: 228,
        TK: 690,
        TO: 676,
        TT: 1868,
        TN: 216,
        TR: 90,
        TM: 993,
        TC: 1649,
        TV: 688,
        VI: 1340,
        UG: 256,
        UA: 380,
        AE: 971,
        GB: 44,
        UY: 598,
        UZ: 998,
        VU: 678,
        VA: 379,
        VE: 58,
        VN: 84,
        WF: 681,
        EH: 212,
        YE: 967,
        ZM: 260,
        ZW: 263
    },
    COUNTRY_DATA = {
        en: buildCountryList(COUNTRY_NAMES_EN),
        ru: buildCountryList(COUNTRY_NAMES_RU)
    };

function buildCountryList(names) {
    return Object.keys(names)
        .map(code => {
            return { code, codeLC: code.toLowerCase(), name: names[code], phone_code: PHONE_CODES[code] };
        })
        .sort((a, b) => a.name.localeCompare(b.name));
}

function getCountryList(lang) {
    return COUNTRY_DATA[lang];
}

function getPhoneCodeFromLib(countryCode) {
    try {
        return getPhoneCode(countryCode);
    } catch {}
}

function getCountryPhoneData(countryCode) {
    const _phoneCode = PHONE_CODES[countryCode],
        phoneCode = '' + _phoneCode,
        phoneCodeLib = getPhoneCodeFromLib(countryCode) || '';

    return { phoneCode: phoneCode.substr(0, phoneCodeLib.length), phoneNumber: phoneCode.substr(phoneCodeLib.length) };
}

function lookupCountryByPhone(code, number) {
    const phoneNumber = code + number,
        countries = Object.keys(PHONE_CODES)
            .filter(c => {
                const _code = '' + PHONE_CODES[c],
                    len = _code.length;

                return (len < 4 ? code.startsWith(_code) : _code.startsWith(code)) && phoneNumber.startsWith(_code);
            })
            .sort((a, b) => PHONE_CODES[b] - PHONE_CODES[a]);

    return countries.length ? countries[0] : '';
}

function getDefaultCountryCode() {
    const lang = window.navigator.language,
        [langCode, countryCode] = lang.split('-'),
        code = (countryCode || langCode).toUpperCase(),
        exists = Boolean(COUNTRY_NAMES_EN[code]);

    return exists ? code : 'US';
}

export { getCountryList, getDefaultCountryCode, getCountryPhoneData, lookupCountryByPhone };
