/*
 *  Copyright (c) 2018-present, Evgeny Nadymov
 *
 * This source code is licensed under the GPL v.3.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Self-destructing SW for development
if (self.location.hostname === 'localhost') {
    self.addEventListener('install', () => {
        self.skipWaiting();
    });
    self.addEventListener('activate', () => {
        self.registration.unregister();
        self.clients.matchAll({ type: 'window' }).then(clients => {
            clients.forEach(client => client.navigate(client.url));
        });
    });
} else {
    // Precache and route all assets generated by the build process
    precacheAndRoute(self.__WB_MANIFEST);

    // Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
    registerRoute(
        ({ url }) => url.origin === 'https://fonts.googleapis.com',
        new StaleWhileRevalidate({
            cacheName: 'google-fonts-stylesheets',
        })
    );

    // Cache the Google Fonts webfont files with a cache-first strategy for 1 year
    registerRoute(
        ({ url }) => url.origin === 'https://fonts.gstatic.com',
        new CacheFirst({
            cacheName: 'google-fonts-webfonts',
            plugins: [
                new ExpirationPlugin({
                    maxAgeSeconds: 60 * 60 * 24 * 365,
                    maxEntries: 30,
                }),
            ],
        })
    );

    // Cache API requests with a network-first strategy
    registerRoute(
        ({ url }) => url.origin.includes('telegram.org'),
        new NetworkFirst({
            cacheName: 'api-cache',
            plugins: [
                new ExpirationPlugin({
                    maxEntries: 100,
                    maxAgeSeconds: 60 * 60 * 24,
                }),
            ],
        })
    );

    // Cache images with a cache-first strategy
    registerRoute(
        ({ request }) => request.destination === 'image',
        new CacheFirst({
            cacheName: 'images',
            plugins: [
                new ExpirationPlugin({
                    maxEntries: 60,
                    maxAgeSeconds: 30 * 24 * 60 * 60,
                }),
            ],
        })
    );

    // Default strategy for other assets
    registerRoute(
        ({ request }) => 
            request.destination === 'script' || 
            request.destination === 'style',
        new StaleWhileRevalidate({
            cacheName: 'static-resources',
        })
    );

    // Skip waiting and clients claim to update service worker immediately
    self.addEventListener('message', (event) => {
        if (event.data && event.data.type === 'SKIP_WAITING') {
            self.skipWaiting();
        }
    });

    self.addEventListener('activate', event => {
        event.waitUntil(self.clients.claim());
    });
} 